import { useCallback, useEffect, useState } from "react";
import { Page } from "./dashboard";
import { request } from "../lib/api";

const initialProfile = { age: "", gender: "", height_cm: "", weight_kg: "", goal: "Fitness", activity_level: "Moderate", diet_preference: "Vegetarian", bio: "" };
const dateTime = (value) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(`${value}Z`)) : "—";

function Notice({ notice }) { return notice ? <p className={`notice ${notice.type}`}>{notice.text}</p> : null; }
function useLoad(path, key) {
  const [state, setState] = useState({ loading: true, data: null, error: "" });
  const reload = useCallback(() => { setState((s) => ({ ...s, loading: true, error: "" })); return request(path).then((data) => setState({ loading: false, data, error: "" })).catch((e) => setState({ loading: false, data: null, error: e.message })); }, [path]);
  useEffect(() => { reload(); }, [reload, key]);
  return { ...state, reload };
}
function FormButton({ busy, children }) { return <button className="button primary" disabled={busy}>{busy ? "Saving…" : children}</button>; }
function NumberField({ label, value, onChange, min, max, step = "1" }) { return <label>{label}<input type="number" min={min} max={max} step={step} value={value} onChange={(e) => onChange(e.target.value)} required /></label>; }

export function CheckinPage() {
  const [form, setForm] = useState({ sleep_hours: "", steps: "", water_glasses: "", mood: "", energy: "", soreness: "", note: "" });
  const [notice, setNotice] = useState(null); const [busy, setBusy] = useState(false);
  const update = (key) => (value) => setForm({ ...form, [key]: value });
  async function submit(e) { e.preventDefault(); setBusy(true); try { await request("/checkins/today", { method: "PUT", body: numbers(form, ["sleep_hours", "steps", "water_glasses", "mood", "energy", "soreness"]) }); setNotice({ type: "success", text: "Today’s check-in is saved. A small honest log is more useful than a perfect one." }); } catch (err) { setNotice({ type: "error", text: err.message }); } finally { setBusy(false); } }
  return <Page><Header eyebrow="DAILY CHECK-IN" title="How are you actually doing?" copy="This takes a minute and helps turn health data into context." /><form className="panel form-grid" onSubmit={submit}>
    <NumberField label="Sleep (hours)" value={form.sleep_hours} onChange={update("sleep_hours")} min="0" max="24" step="0.5" /><NumberField label="Steps" value={form.steps} onChange={update("steps")} min="0" max="100000" />
    <NumberField label="Water (glasses)" value={form.water_glasses} onChange={update("water_glasses")} min="0" max="30" /><Scale label="Mood" value={form.mood} onChange={update("mood")} hint="1 = low · 5 = great" />
    <Scale label="Energy" value={form.energy} onChange={update("energy")} hint="1 = drained · 5 = strong" /><Scale label="Soreness" value={form.soreness} onChange={update("soreness")} hint="1 = none · 5 = high" />
    <label className="span-all">Anything worth remembering?<textarea value={form.note} onChange={(e) => update("note")(e.target.value)} placeholder="For example: busy day, slept late, workout felt good…" /></label><Notice notice={notice} /><FormButton busy={busy}>Save today’s check-in</FormButton>
  </form></Page>;
}

export function BMIPage() {
  const [weight, setWeight] = useState(""); const [height, setHeight] = useState(""); const [record, setRecord] = useState(null); const [notice, setNotice] = useState(null); const [busy, setBusy] = useState(false);
  const getBMIStatus = (category) => {
    if (!category) return null;
    const cat = category.toLowerCase();
    if (cat.includes("normal")) return { color: "green", label: "Optimal" };
    if (cat.includes("overweight") || cat.includes("underweight")) return { color: "amber", label: "Moderate" };
    return { color: "red", label: "High Risk" };
  };
  async function submit(e) { e.preventDefault(); setBusy(true); try { const data = await request("/records/bmi", { method: "POST", body: { weight_kg: Number(weight), height_cm: Number(height) } }); setRecord(data.record); setNotice({ type: "success", text: "BMI measurement saved to your private history." }); } catch (err) { setNotice({ type: "error", text: err.message }); } finally { setBusy(false); } }
  const bmiStatus = getBMIStatus(record?.category);
  return <Page><Header eyebrow="BODY METRIC" title="BMI, with context." copy="BMI is a screening estimate, not a diagnosis or complete picture of health." /><div className="two-column"><form className="panel form-stack" onSubmit={submit}><NumberField label="Weight (kg)" value={weight} onChange={setWeight} min="20" max="400" step="0.1" /><NumberField label="Height (cm)" value={height} onChange={setHeight} min="80" max="250" step="0.1" /><Notice notice={notice} /><FormButton busy={busy}>Calculate and save</FormButton></form><section className="panel result-panel">{record ? <><p className="label">YOUR RESULT</p><div className="hero-number">{record.bmi}</div><h2 style={{display: "flex", alignItems: "center", gap: "0.5rem"}}>{record.category} {bmiStatus && <span className={`metric-card-status status-${bmiStatus.color}`}>● {bmiStatus.label}</span>}</h2><p>{record.guidance}</p><p className="muted">Use changes over time and professional advice—not one number alone.</p></> : <EmptyMessage text="Enter height and weight to calculate your BMI." />}</section></div></Page>;
}

export function FoodPage() {
  const [form, setForm] = useState({ food_name: "", calories: "", protein_g: "", carbs_g: "", fat_g: "", note: "" }); const [notice, setNotice] = useState(null); const [busy, setBusy] = useState(false); const [preview, setPreview] = useState(null); const [base64Image, setBase64Image] = useState(null); const [analyzing, setAnalyzing] = useState(false);
  const update = (key) => (value) => setForm({ ...form, [key]: value });
  const handleFile = (e) => { const file = e.target.files?.[0]; if (file) { setPreview(URL.createObjectURL(file)); const reader = new FileReader(); reader.onloadend = () => setBase64Image(reader.result); reader.readAsDataURL(file); } else { setPreview(null); setBase64Image(null); } };
  async function analyzeFood() { if (!base64Image) return; setAnalyzing(true); setNotice(null); try { const data = await request("/analyze-food", { method: "POST", body: { image: base64Image } }); setForm(prev => ({ ...prev, food_name: data.food_name || prev.food_name, calories: data.calories?.toString() || prev.calories, protein_g: data.protein_g?.toString() || prev.protein_g, carbs_g: data.carbs_g?.toString() || prev.carbs_g, fat_g: data.fat_g?.toString() || prev.fat_g })); setNotice({ type: "success", text: "AI analysis complete! You can tweak the values before saving." }); } catch (err) { setNotice({ type: "error", text: "AI Analysis failed: " + err.message }); } finally { setAnalyzing(false); } }
  async function submit(e) { e.preventDefault(); setBusy(true); try { await request("/records/food", { method: "POST", body: numbers(form, ["calories", "protein_g", "carbs_g", "fat_g"]) }); setNotice({ type: "success", text: "Food log added to today’s nutrition totals." }); setForm({ food_name: "", calories: "", protein_g: "", carbs_g: "", fat_g: "", note: "" }); setPreview(null); setBase64Image(null); } catch (err) { setNotice({ type: "error", text: err.message }); } finally { setBusy(false); } }
  return <Page><Header eyebrow="FOOD SCANNER & LOG" title="Photo-assisted food logging." copy="Take or upload a photo of your meal. The AI will estimate the nutrition, which you can adjust before saving." /><div className="two-column"><form className="panel form-grid" onSubmit={submit}><label className="span-all upload-box">Food photo<input type="file" accept="image/*" onChange={handleFile} />{preview && <img src={preview} alt="Selected food" />}</label>{base64Image && <div className="span-all"><button type="button" className="button secondary" onClick={analyzeFood} disabled={analyzing}>{analyzing ? "Analyzing..." : "Analyze Photo with AI"}</button></div>}<label className="span-all">Food / meal name<input required value={form.food_name} onChange={(e) => update("food_name")(e.target.value)} placeholder="e.g. Dal rice with salad" /></label><NumberField label="Calories (kcal)" value={form.calories} onChange={update("calories")} min="0" max="10000" /><NumberField label="Protein (g)" value={form.protein_g} onChange={update("protein_g")} min="0" max="1000" step="0.1" /><NumberField label="Carbohydrates (g)" value={form.carbs_g} onChange={update("carbs_g")} min="0" max="1000" step="0.1" /><NumberField label="Fat (g)" value={form.fat_g} onChange={update("fat_g")} min="0" max="1000" step="0.1" /><label className="span-all">Notes<textarea value={form.note} onChange={(e) => update("note")(e.target.value)} placeholder="Portion, preparation, or how you felt after eating" /></label><Notice notice={notice} /><FormButton busy={busy}>Add food log</FormButton></form><section className="panel"><p className="label">ESTIMATING WELL</p><h2>AI is an assistant, not magic.</h2><ol className="plain-list"><li>Ensure good lighting in your photos.</li><li>AI might miss hidden ingredients like extra oils.</li><li>Review the AI's numbers and tweak them if they seem off.</li></ol><p className="muted">Image-based estimates can be wrong, particularly for mixed dishes.</p></section></div></Page>;
}

export function SkinPage() {
  const [summary, setSummary] = useState(""); const [concerns, setConcerns] = useState([]); const [notice, setNotice] = useState(null); const [busy, setBusy] = useState(false);
  const [preview, setPreview] = useState(null); const [base64Image, setBase64Image] = useState(null); const [analyzing, setAnalyzing] = useState(false);
  const options = ["Acne / pimples", "Dryness", "Oiliness", "Redness", "Pigmentation", "Dark circles"];
  const handleFile = (e) => { const file = e.target.files?.[0]; if (file) { setPreview(URL.createObjectURL(file)); const reader = new FileReader(); reader.onloadend = () => setBase64Image(reader.result); reader.readAsDataURL(file); } else { setPreview(null); setBase64Image(null); } };
  async function analyzeSkin() { if (!base64Image) return; setAnalyzing(true); setNotice(null); try { const data = await request("/analyze-skin", { method: "POST", body: { image: base64Image } }); if (data.concerns) { setConcerns(prev => Array.from(new Set([...prev, ...data.concerns.filter(c => options.includes(c))]))); } if (data.summary) { setSummary(prev => prev ? prev + "\n\nAI Notes: " + data.summary : "AI Notes: " + data.summary); } setNotice({ type: "success", text: "AI skin analysis complete! Review the notes before saving." }); } catch (err) { setNotice({ type: "error", text: "AI Analysis failed: " + err.message }); } finally { setAnalyzing(false); } }
  async function submit(e) { e.preventDefault(); setBusy(true); try { await request("/records/skin", { method: "POST", body: { summary, concerns } }); setNotice({ type: "success", text: "Private skin note saved. It is not a diagnosis." }); setSummary(""); setConcerns([]); setPreview(null); setBase64Image(null); } catch (err) { setNotice({ type: "error", text: err.message }); } finally { setBusy(false); } }
  return <Page><Header eyebrow="SKIN JOURNAL" title="Notice patterns safely." copy="Upload a photo to let AI help log cosmetic observations. Persistent, painful, sudden, or concerning changes deserve a clinician’s input." /><div className="two-column"><form className="panel form-stack" onSubmit={submit}><label className="upload-box">Optional skin photo<input type="file" accept="image/*" onChange={handleFile} />{preview && <img src={preview} alt="Skin" />}</label>{base64Image && <button type="button" className="button secondary" onClick={analyzeSkin} disabled={analyzing}>{analyzing ? "Analyzing..." : "Analyze Photo with AI"}</button>}<fieldset><legend>What are you noticing?</legend><div className="choice-grid">{options.map((item) => <label className="check-choice" key={item}><input type="checkbox" checked={concerns.includes(item)} onChange={() => setConcerns(concerns.includes(item) ? concerns.filter((x) => x !== item) : [...concerns, item])} />{item}</label>)}</div></fieldset><label>Notes<textarea required minLength="2" value={summary} onChange={(e) => setSummary(e.target.value)} placeholder="When it started, products used, discomfort, and anything that changed…" /></label><Notice notice={notice} /><FormButton busy={busy}>Save skin note</FormButton></form><section className="panel safety-panel"><p className="label">WHEN TO GET HELP</p><h2>Don’t wait on an app for urgent symptoms.</h2><p>Seek professional care for severe swelling, breathing difficulty, rapidly spreading rash, significant pain, fever, signs of infection, or anything worrying you.</p><p className="muted">Health.io never diagnoses from photos or recommends prescription treatment.</p></section></div></Page>;
}

export function MealPlannerPage() {
  const [form, setForm] = useState({ goal: "Fitness", diet_type: "Vegetarian", budget: "", meals_per_day: "4", extra_instructions: "" }); const [plan, setPlan] = useState(null); const [notice, setNotice] = useState(null); const [busy, setBusy] = useState(false); const { data, reload } = useLoad("/meal-plans", "plans");
  const update = (key) => (value) => setForm({ ...form, [key]: value });
  async function submit(e) { e.preventDefault(); setBusy(true); try { const result = await request("/meal-plans", { method: "POST", body: { ...form, budget: form.budget ? Number(form.budget) : null, meals_per_day: Number(form.meals_per_day) } }); setPlan(result.meal_plan); reload(); setNotice({ type: "success", text: "Your practical meal plan is ready and saved." }); } catch (err) { setNotice({ type: "error", text: err.message }); } finally { setBusy(false); } }
  return <Page><Header eyebrow="MEAL PLANNER" title="Plan for real life, not perfection." copy="Plans are general guidance. For medical nutrition needs, consult a registered dietitian." /><div className="two-column"><form className="panel form-grid" onSubmit={submit}><label>Goal<select value={form.goal} onChange={(e) => update("goal")(e.target.value)}><option>Fat Loss</option><option>Muscle Gain</option><option>Fitness</option></select></label><label>Diet<select value={form.diet_type} onChange={(e) => update("diet_type")(e.target.value)}><option>Vegetarian</option><option>Non-vegetarian</option><option>Vegan</option><option>Eggetarian</option></select></label><NumberField label="Daily budget (optional, Rs.)" value={form.budget} onChange={update("budget")} min="0" max="100000" /><label>Meals per day<select value={form.meals_per_day} onChange={(e) => update("meals_per_day")(e.target.value)}>{[2,3,4,5,6].map((n) => <option key={n}>{n}</option>)}</select></label><label className="span-all">Preferences / constraints<textarea value={form.extra_instructions} onChange={(e) => update("extra_instructions")(e.target.value)} placeholder="Foods you dislike, schedule constraints, allergies to discuss with a professional…" /></label><Notice notice={notice} /><FormButton busy={busy}>Generate meal plan</FormButton></form><PlanCard plan={plan} /></div><section className="history-section"><p className="label">SAVED PLANS</p>{data?.meal_plans?.length ? data.meal_plans.map((item) => <details className="saved-item" key={item.id}><summary>{item.goal} · {item.diet_type}<time>{dateTime(item.created_at)}</time></summary><PlanText text={item.plan_text} /></details>) : <p className="muted">Saved meal plans will appear here.</p>}</section></Page>;
}

export function WorkoutPage() {
  const [form, setForm] = useState({ goal: "Fitness", level: "Beginner", location: "Home", duration_minutes: "30", rest_seconds: "30", weight_kg: "70" }); const [workout, setWorkout] = useState(null); const [notice, setNotice] = useState(null); const [busy, setBusy] = useState(false);
  const update = (key) => (value) => setForm({ ...form, [key]: value });
  async function generate(e) { e.preventDefault(); setBusy(true); try { const result = await request("/workouts/generate", { method: "POST", body: numbers(form, ["duration_minutes", "rest_seconds", "weight_kg"]) }); setWorkout(result.workout); setNotice({ type: "success", text: "Workout generated. Read the form cues before starting." }); } catch (err) { setNotice({ type: "error", text: err.message }); } finally { setBusy(false); } }
  async function complete() { if (!workout) return; setBusy(true); try { const calories = workout.exercises.reduce((total, item) => total + item.estimated_calories, 0); await request(`/workouts/${workout.id}/complete`, { method: "POST", body: { total_calories: calories } }); setNotice({ type: "success", text: "Workout saved as completed. Nice work showing up." }); } catch (err) { setNotice({ type: "error", text: err.message }); } finally { setBusy(false); } }
  return <Page><Header eyebrow="WORKOUT PLANNER" title="A session you can explain—and do." copy="Generated plans are conservative general fitness guidance. Stop for sharp pain, dizziness, chest pain, or unusual breathlessness." /><div className="two-column"><form className="panel form-grid" onSubmit={generate}><Select label="Goal" value={form.goal} onChange={update("goal")} options={["Fat Loss", "Muscle Gain", "Fitness"]} /><Select label="Experience" value={form.level} onChange={update("level")} options={["Beginner", "Intermediate", "Advanced"]} /><Select label="Location" value={form.location} onChange={update("location")} options={["Home", "Gym"]} /><NumberField label="Duration (minutes)" value={form.duration_minutes} onChange={update("duration_minutes")} min="15" max="120" /><NumberField label="Rest (seconds)" value={form.rest_seconds} onChange={update("rest_seconds")} min="10" max="120" /><NumberField label="Body weight (kg)" value={form.weight_kg} onChange={update("weight_kg")} min="20" max="400" step="0.1" /><Notice notice={notice} /><FormButton busy={busy}>Build workout</FormButton></form><section className="panel">{workout ? <><p className="label">YOUR SESSION</p><h2>{workout.goal} · {workout.duration_minutes} min</h2><ol className="workout-list">{workout.exercises.map((exercise) => <li key={exercise.name}><div><b>{exercise.name}</b><span>{exercise.sets} · {exercise.seconds}s · rest {exercise.rest_seconds}s</span><small>{exercise.form_cue}</small></div><a href={exercise.video_search} target="_blank" rel="noreferrer">Form guide ↗</a></li>)}</ol><button className="button primary" disabled={busy} onClick={complete}>Mark workout complete</button></> : <EmptyMessage text="Choose your preferences to build a structured session." />}</section></div></Page>;
}

export function AnalyticsPage() {
  const { data, loading, error, reload } = useLoad("/workouts", "workouts"); const workouts = data?.workouts || []; const completed = workouts.filter((item) => item.completed_at); const totalMinutes = completed.reduce((sum, item) => sum + item.duration_minutes, 0); const totalCalories = completed.reduce((sum, item) => sum + item.total_calories, 0);
  return <Page><Header eyebrow="WORKOUT ANALYTICS" title="Progress is a history, not a mood." copy="Review completed sessions and use patterns to adjust your next week." />{error && <div className="notice error">{error}<button onClick={reload}>Try again</button></div>}{loading ? <p className="loading">Loading sessions…</p> : <><div className="stat-grid"><Metric label="Completed sessions" value={completed.length} /><Metric label="Minutes trained" value={totalMinutes} /><Metric label="Estimated kcal" value={Math.round(totalCalories)} /><Metric label="Plans generated" value={workouts.length} /></div><section className="panel"><p className="label">SESSION HISTORY</p>{workouts.length ? <div className="table-list">{workouts.map((item) => <article key={item.id}><div><b>{item.goal}</b><span>{item.level} · {item.location} · {item.duration_minutes} min</span></div><div><span>{item.completed_at ? "Completed" : "Planned"}</span><time>{dateTime(item.completed_at || item.created_at)}</time></div></article>)}</div> : <EmptyMessage text="Finish a workout to see useful trends here." />}</section></>}</Page>;
}

export function HistoryPage() {
  const { data, loading, error, reload } = useLoad("/records", "records"); const [filter, setFilter] = useState("ALL"); const records = (data?.records || []).filter((record) => filter === "ALL" || record.type === filter);
  return <Page><Header eyebrow="HEALTH HISTORY" title="Your private record." copy="Records are visible only to the signed-in account in this local setup." /><div className="filter-row">{["ALL", "BMI", "FOOD", "SKIN"].map((type) => <button className={filter === type ? "selected" : ""} onClick={() => setFilter(type)} key={type}>{type === "ALL" ? "All activity" : type}</button>)}</div>{error && <div className="notice error">{error}<button onClick={reload}>Try again</button></div>}{loading ? <p className="loading">Loading your history…</p> : <div className="form-stack">{records.length ? records.map((record) => <HistoryItem record={record} key={`${record.type}-${record.id}`} />) : <EmptyMessage text="No records match this view yet." />}</div>}</Page>;
}

export function ProfilePage() {
  const { data, loading, error, reload } = useLoad("/me", "me"); const [form, setForm] = useState(initialProfile); const [notice, setNotice] = useState(null); const [busy, setBusy] = useState(false);
  useEffect(() => { if (data?.profile) setForm({ ...initialProfile, ...Object.fromEntries(Object.entries(data.profile).filter(([key]) => key in initialProfile).map(([key, value]) => [key, value ?? ""])) }); }, [data]);
  const update = (key) => (value) => setForm({ ...form, [key]: value });
  async function submit(e) { e.preventDefault(); setBusy(true); try { await request("/profile", { method: "PUT", body: nullableNumbers(form, ["age", "height_cm", "weight_kg"]) }); setNotice({ type: "success", text: "Profile saved. Future planning and guidance can use these preferences." }); reload(); } catch (err) { setNotice({ type: "error", text: err.message }); } finally { setBusy(false); } }
  if (loading) return <Page><p className="loading">Loading profile…</p></Page>;
  return <Page><Header eyebrow="YOUR PROFILE" title={data?.user?.display_name || "Your profile"} copy="Only share what you’re comfortable using for personal planning. You can update this at any time." />{error && <div className="notice error">{error}</div>}<form className="panel form-grid" onSubmit={submit}><NumberField label="Age" value={form.age} onChange={update("age")} min="13" max="120" /><Select label="Gender (optional)" value={form.gender} onChange={update("gender")} options={["", "Female", "Male", "Non-binary", "Prefer not to say"]} /><NumberField label="Height (cm)" value={form.height_cm} onChange={update("height_cm")} min="80" max="250" step="0.1" /><NumberField label="Weight (kg)" value={form.weight_kg} onChange={update("weight_kg")} min="20" max="400" step="0.1" /><Select label="Goal" value={form.goal} onChange={update("goal")} options={["Fat Loss", "Muscle Gain", "Fitness", "Better routine"]} /><Select label="Activity level" value={form.activity_level} onChange={update("activity_level")} options={["Low", "Light", "Moderate", "High"]} /><Select label="Diet preference" value={form.diet_preference} onChange={update("diet_preference")} options={["Vegetarian", "Non-vegetarian", "Vegan", "Eggetarian", "No preference"]} /><label className="span-all">About your routine<textarea value={form.bio} onChange={(e) => update("bio")(e.target.value)} placeholder="Schedule, preferences, or context you want to remember" /></label><Notice notice={notice} /><FormButton busy={busy}>Save profile</FormButton></form></Page>;
}

export function ChatPage() {
  const { data, loading, error, reload } = useLoad("/chat", "chat"); const [message, setMessage] = useState(""); const [notice, setNotice] = useState(null); const [busy, setBusy] = useState(false);
  async function submit(e) { e.preventDefault(); if (!message.trim()) return; setBusy(true); try { await request("/chat", { method: "POST", body: { message } }); setMessage(""); reload(); } catch (err) { setNotice({ type: "error", text: err.message }); } finally { setBusy(false); } }
  async function clear() { if (!window.confirm("Clear this chat history?")) return; await request("/chat", { method: "DELETE" }); reload(); }
  return <Page><Header eyebrow="AI WELLNESS ASSISTANT" title="Ask, then act on one thing." copy="This assistant gives general wellness information. It does not diagnose, prescribe, or replace professional care." /><section className="panel chat-panel">{error && <Notice notice={{ type: "error", text: error }} />}{loading ? <p className="loading">Loading conversation…</p> : <div className="messages">{data?.messages?.length ? data.messages.map((item) => <article className={`message ${item.role}`} key={item.id}><b>{item.role === "user" ? "You" : "Health.io"}</b><MarkdownMessage content={item.content} /></article>) : <EmptyMessage text="Ask about a small fitness, nutrition, or routine goal." />}</div>}<form className="chat-form" onSubmit={submit}><textarea value={message} maxLength="1500" onChange={(e) => setMessage(e.target.value)} placeholder="Ask a general wellness question…" /><FormButton busy={busy}>Send</FormButton><button type="button" className="button secondary" onClick={clear}>Clear chat</button></form><Notice notice={notice} /></section></Page>;
}

function Header({ eyebrow, title, copy }) { return <header className="page-header"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></header>; }
function MarkdownMessage({ content }) {
  if (!content) return null;
  const html = content
    .replace(/</g, "&lt;").replace(/>/g, "&gt;") // sanitize basic
    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>") // bold
    .replace(/\*(.*?)\*/g, "<em>$1</em>") // italic
    .replace(/^(?:-|\*)\s+(.*)/gm, "<li>$1</li>") // list items
    .replace(/(<li>.*<\/li>(?:\n<li>.*<\/li>)*)/g, "<ul class='chat-list'>$1</ul>") // wrap in ul
    .replace(/\n/g, "<br />"); // line breaks

  return <div className="message-content" dangerouslySetInnerHTML={{ __html: html }} />;
}
function EmptyMessage({ text }) { return <p className="muted empty-message">{text}</p>; }
function Select({ label, value, onChange, options }) { return <label>{label}<select value={value} onChange={(e) => onChange(e.target.value)}>{options.map((option) => <option key={option} value={option}>{option || "Select"}</option>)}</select></label>; }
function Scale({ label, value, onChange, hint }) { return <label>{label}<select required value={value} onChange={(e) => onChange(e.target.value)}><option value="">Choose</option>{[1,2,3,4,5].map((n) => <option key={n}>{n}</option>)}</select><small>{hint}</small></label>; }
function Metric({ label, value }) { return <article className="metric-card"><p>{label}</p><strong>{value}</strong></article>; }
function PlanCard({ plan }) { return <section className="panel plan-card">{plan ? <><p className="label">YOUR SAVED PLAN</p><h2>{plan.goal} · {plan.diet_type}</h2><PlanText text={plan.plan_text} /></> : <EmptyMessage text="Your generated plan will stay here and be saved in your history." />}</section>; }
function PlanText({ text }) { return <div className="plan-text">{text.split("\n").map((line, index) => line.startsWith("## ") ? <h3 key={index}>{line.slice(3)}</h3> : line ? <p key={index}>{line.replace(/^- /, "• ")}</p> : <br key={index} />)}</div>; }
function HistoryItem({ record }) { const title = record.type === "BMI" ? `BMI ${record.bmi} · ${record.category}` : record.type === "FOOD" ? record.food_name : record.concerns?.join(", ") || "Skin note"; return <article className="panel" style={{ display: "flex", justifyContent: "space-between", gap: "1.5rem", alignItems: "center" }}><div><h2 style={{margin: 0, fontSize: "1.2rem"}}>{title}</h2><span style={{opacity: 0.8, display: "block", marginTop: "0.25rem"}}>{record.type === "FOOD" ? `${record.calories} kcal · ${record.protein_g}g protein` : record.summary || record.guidance || "Saved health record"}</span></div><time style={{fontSize: "0.85rem", opacity: 0.7, whiteSpace: "nowrap"}}>{dateTime(record.created_at)}</time></article>; }
function numbers(form, fields) { const result = { ...form }; fields.forEach((field) => { result[field] = Number(result[field]); }); return result; }
function nullableNumbers(form, fields) { const result = { ...form }; fields.forEach((field) => { result[field] = result[field] === "" ? null : Number(result[field]); }); return result; }
